import type { EventRegion } from '@/data/events'

/** Lowercased country name → UI region (best-effort; defaults to americas). */
const COUNTRY_REGION: Record<string, EventRegion> = {
  // Americas
  'united states': 'americas',
  usa: 'americas',
  canada: 'americas',
  mexico: 'americas',
  brazil: 'americas',
  argentina: 'americas',
  colombia: 'americas',
  peru: 'americas',
  chile: 'americas',
  uruguay: 'americas',
  bolivia: 'americas',
  ecuador: 'americas',
  'el salvador': 'americas',
  'costa rica': 'americas',
  panama: 'americas',
  guatemala: 'americas',
  honduras: 'americas',
  nicaragua: 'americas',
  paraguay: 'americas',
  venezuela: 'americas',
  jamaica: 'americas',
  'trinidad and tobago': 'americas',
  'dominican republic': 'americas',
  'puerto rico': 'americas',

  // Europe
  'united kingdom': 'europe',
  uk: 'europe',
  england: 'europe',
  scotland: 'europe',
  ireland: 'europe',
  france: 'europe',
  germany: 'europe',
  netherlands: 'europe',
  belgium: 'europe',
  spain: 'europe',
  portugal: 'europe',
  italy: 'europe',
  switzerland: 'europe',
  austria: 'europe',
  poland: 'europe',
  'czech republic': 'europe',
  czechia: 'europe',
  hungary: 'europe',
  romania: 'europe',
  bulgaria: 'europe',
  greece: 'europe',
  sweden: 'europe',
  norway: 'europe',
  denmark: 'europe',
  finland: 'europe',
  iceland: 'europe',
  estonia: 'europe',
  latvia: 'europe',
  lithuania: 'europe',
  croatia: 'europe',
  serbia: 'europe',
  slovenia: 'europe',
  slovakia: 'europe',
  albania: 'europe',
  'bosnia and herzegovina': 'europe',
  ukraine: 'europe',
  moldova: 'europe',
  turkey: 'europe',
  russia: 'europe',
  luxembourg: 'europe',
  malta: 'europe',
  cyprus: 'europe',

  // Africa
  kenya: 'africa',
  nigeria: 'africa',
  'south africa': 'africa',
  egypt: 'africa',
  ghana: 'africa',
  uganda: 'africa',
  ethiopia: 'africa',
  morocco: 'africa',
  tunisia: 'africa',
  rwanda: 'africa',
  'ivory coast': 'africa',
  senegal: 'africa',
  zimbabwe: 'africa',
  zambia: 'africa',
  botswana: 'africa',
  namibia: 'africa',
  tanzania: 'africa',

  // Middle East
  'united arab emirates': 'middleEast',
  uae: 'middleEast',
  israel: 'middleEast',
  'saudi arabia': 'middleEast',
  qatar: 'middleEast',
  kuwait: 'middleEast',
  bahrain: 'middleEast',
  oman: 'middleEast',
  jordan: 'middleEast',
  lebanon: 'middleEast',
  iraq: 'middleEast',
  iran: 'middleEast',

  // Asia
  india: 'asia',
  china: 'asia',
  japan: 'asia',
  'south korea': 'asia',
  korea: 'asia',
  singapore: 'asia',
  malaysia: 'asia',
  thailand: 'asia',
  vietnam: 'asia',
  philippines: 'asia',
  indonesia: 'asia',
  pakistan: 'asia',
  bangladesh: 'asia',
  'sri lanka': 'asia',
  nepal: 'asia',
  'hong kong': 'asia',
  taiwan: 'asia',
  azerbaijan: 'asia',
  kazakhstan: 'asia',
  uzbekistan: 'asia',
  georgia: 'asia',
  armenia: 'asia',

  // Oceania
  australia: 'oceania',
  'new zealand': 'oceania',
  fiji: 'oceania',
}

export function regionFromCountry(country: string): EventRegion {
  const k = country.toLowerCase().trim()
  return COUNTRY_REGION[k] ?? 'americas'
}
